name: GitHubPages

# Only run this when the master branch changes
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

#    - name: Install dependencies
#      run: |
#        python -m pip install -r docs/requirements.txt
#
#    - name: Build pages
#      run: |
#        make pages

    # Standard drop-in approach that should work for most people.
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "sources/"
